import Head from 'next/head'
import React, {  useEffect, useState } from 'react'
import { setEnvironmentData } from 'worker_threads';
import ItemBook from './book/bookitem';

export default function Home() {
  const [newBook, setnewBook] = useState("");
  const [callData, isData] = useState([]);
  useEffect(() => {
    fetchData();
  }, [newBook]);

  async function fetchData() {
    const res = await fetch("../api/getData");
    const newData = await res.json();

  }

  return (
    <>
      <Head>
        <title>Test CRUD In Next.JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-center font-bold text-3xl'>Book Collection</h1>
      <div>
        <ItemBook />
      </div>
    </>
  )
}


